config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback', to: 'sessions#github_create'
  get '/auth/google_oauth2/callback', to: 'sessions#google_create'
  get '/auth/twitter/callback', to: 'sessions#twitter_create'
  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#home'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/user' => 'users#show'

  get '/all_restaurants_in_database' => 'locations#all_restaurants_in_db'

  resources :locations
  resources :restaurants
  resources :items

  resources :restaurants, only: [:show, :index] do
    resources :items
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :locations
  has_many :items
  has_many :users, through: :locations

  validates_presence_of :name, { message: "Name can't be blank"}
  validate :rating_not_higher_than_five

  accepts_nested_attributes_for :locations

  def self.search(search)
    if search
      restaurant = Restaurant.find_by(state: search)
      if restaurant
        self.where(state: restaurant.state)
      else
        self.all
      end
    else
      self.all
    end
  end

  def city_and_state
    if self.city == nil || self.city == ""
      self.state
    else
      self.city + ", " + self.state
    end
  end

  def self.options
    self.select(:state).distinct.order(:state)
  end

  def rating_not_higher_than_five
    if rating.to_i > 5 || rating.to_i < 1
     errors.add(:rating, "Rating must be between 1 and 5")
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login
  skip_before_action :verify_authenticity_token

  def index
    all_restaurants = current_user.restaurants.uniq
    @restaurants = all_restaurants.sort_by {|r| r.name.downcase}
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @restaurants}
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @restaurant}
    end
  end

  def new
    @restaurant = Restaurant.new
    @restaurant.locations.build
    @user = current_user
  end

  def create
    @user = current_user
    @restaurant = Restaurant.new(restaurant_params)
    @restaurants = current_user.restaurants.uniq
    if @restaurant.save
      render json: @restaurant, status: 201
    else
      render :new
    end
  end

  def edit
    restaurants = current_user.restaurants.uniq
    result = restaurants.select { |r|  r.id == params[:id].to_i  }
    if result == []
      redirect_to restaurants_path
    else
      @restaurant = Restaurant.find(params[:id])
      @user = current_user
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @user = current_user
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    Location.find_by(restaurant_id: params[:id]).destroy
    Restaurant.find(params[:id]).destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :price_range, :reservations, :query_search, :query_existing, :parking, :wifi, :city, :state, :occasion, :takeS_reservations, :location_id, :rating, :comment, locations_attributes: [:city, :state, :user_id])
  end
end

app/views/restaurants/all_with_wifi.html.erb
List of All Restaurants in the Database with Wifi
<br> filter for state?
<% @restaurants.each do |r| %>
  <h4><%= link_to r.name, restaurant_path(r) %> </h4>
  <ul>
    <li>Price Range: <%= r.price_range %> </li>
    <li>Parking: <%= r.parking %> </li>
    <li>Good For: <%= r.occasion %> </li>
    <li>Takes Reservations: <%= r.takeS_reservations %> </li>
    <li> Location: <%=r.locations.last.city_and_state %> </li>
  </ul>
<% end %>

app/views/restaurants/edit.html.erb
<h1><i>Please enter your updates</i></h1>

<% if @restaurant.errors.any? %>
     <h2>Unfortunately, there were some errors. Please try again. </h2>
     <ul>
       <% @restaurant.errors.messages.each do |message| %>
         <li><%= message[1].join %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>

<%= f.label :price_range, "Price Range" %>
<%= f.text_field :price_range %> <br>

<%= f.label :takeS_reservations, "Takes Reservations?" %>
<%= f.select :takeS_reservations, options_for_select(["", "Yes", "No"], @restaurant.takeS_reservations)%> <br>

<%= f.label :parking %>
<%= f.text_field :parking %> <br>

<%= f.label :wifi, "Wifi?"%>
<%= f.select :wifi, options_for_select(["", "Yes", "No"], @restaurant.wifi)%> <br>

<%= f.label :occasion %>
<%= f.select :occasion, options_for_select(["", "Full Meal", "Fast Food", "Casual", "Brewery", "Small Plates", "Drinks", "Other"], @restaurant.occasion)%> <br>

<%= f.label :rating, "Rating (Out of 5)" %>
<%= f.text_field :rating %> <br>

<%= f.label :comment %>
<%= f.text_field :comment %> <br><br>

<%= f.submit "Submit", :class => 'submit-button'%>
<% end %>

app/views/restaurants/index.html.erb
<h2>Welcome <span class="blue"><%= current_user.username %>!</span> You are successfully logged in.</h2>
<i>Please note you are only able to add, edit, or delete if restaurants or items are under your account</i>
<br>
<% @restaurants.each do |r| %>
  <div>
  <span class='rest-name'><%=link_to r.name, restaurant_path(r) %> - <%= r.locations.first.state %></span>
    <div class="itemNames-<%=r.id%> rest-items"></div>
    <button class="show" data-id="<%= r.id %>">Show Menu</button>
    <button class="hide" data-id="<%= r.id %>">Hide Menu</button>
  </div>
  <br>
<% end %>

<%= button_to "Create New Restaurant", new_restaurant_path, method: :get, :class => 'submit-button'%><br>
  

app/views/restaurants/new.html.erb
<h1>Where Have You Visited?</h1>
<i>Name, rating, and state are required</i>

<p class='new-rest-form'>
  <% if @restaurant.errors.any? %>
      <h2>Unfortunately, there were some errors. Please try again. </h2>
      <ul>
        <% @restaurant.errors.messages.each do |message| %>
          <li><%= message[1].join %></li>
        <% end %>
      </ul>
  <% end %>

  <%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :price_range, "Price Range" %>
  <%= f.text_field :price_range %> <br>

  <%= f.label :takeS_reservations, "Takes Reservations?" %>
  <%= f.select :takeS_reservations, options_for_select(["", "Yes", "No"])%> <br>

  <%= f.label :parking %>
  <%= f.text_field :parking %> <br>

  <%= f.label :wifi, "Wifi?"%>
  <%= f.select :wifi, options_for_select(["", "Yes", "No"])%> <br>

  <%= f.label :occasion %>
  <%= f.select :occasion, options_for_select(["", "Full Meal", "Diner", "Fast Food", "Casual", "Brewery", "Small Plates", "Drinks", "Other"])%> <br>

  <%= f.label :rating, "Rating (Out of 5)" %>
  <%= f.text_field :rating %> <br>

  <%= f.label :comment %>
  <%= f.text_field :comment %> <br><br>
  <i>Please note you will be unable to edit the locations after this page.</i>
  <%= f.fields_for :locations do |l| %>
    <p><%= l.label :city %>
    <%= l.text_field :city %>

    <%= l.label :state %>
    <%= l.text_field :state %></p>

    <%= l.hidden_field :user_id, :value => @user.id%>
  <% end %>
  <br>

  <%= f.submit "Submit", :class => 'submit-button'%>
  <% end %>
</p>

<div id="restResult">
</div>

<br> <%= link_to "#{fa_icon "undo"}".html_safe + " All Restaurants", restaurants_path, class: "rest-show-link"   %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> </h1>
<ul>
  <li>Good for: <%=@restaurant.occasion %> </li>
  <li>Price Range: <%=@restaurant.price_range %> </li>
  <li>Accepts reservations? <%=@restaurant.takeS_reservations %> </li>
  <li>Has Wifi? <%= @restaurant.wifi %> </li>

  <li>Location(s): <% @restaurant.locations.each do |l| %>
    <%= l.city_and_state %>
  <% end %> </li>
  <li>Rating (Out of 5): <%= @restaurant.rating %> </li>
  <li>Comments: <%=@restaurant.comment %> </li>
  <li>Menu Items: <% @restaurant.items.each do |i| %>
    <ul>
      <li><%= i.name %> <a href="#" class="js-item-detail" data-id="<%= i.id %>" rest-id="<%= @restaurant.id %>"><%= fa_icon "info-circle" %></a>
        <% if current_user.id == @restaurant.locations.first.user_id %>
          <%= link_to "#{fa_icon "edit"}".html_safe, edit_restaurant_item_path(@restaurant, i) %>
          <%= link_to "#{fa_icon "trash"}".html_safe, restaurant_item_path(@restaurant, i), method: :delete%>  </li>
          <% end %>
        <div class="itemVeg-<%=i.id%>"></div>
        <div class="itemCalories-<%=i.id%>"></div>
        <div class="itemPrice-<%=i.id%>"></div>
        <div class="itemCategory-<%=i.id%>"></div>
    </ul>
  <% end %> </li>
</ul>

<% if current_user.id == @restaurant.locations.first.user_id %>
  <%= link_to "#{fa_icon "plus"}".html_safe + " Item", new_restaurant_item_path(@restaurant), class: "rest-show-link" %><br>
  <%= link_to "#{fa_icon "edit"}".html_safe + " " +@restaurant.name, edit_restaurant_path(@restaurant), class: "rest-show-link"  %><br>
  <%= link_to "#{fa_icon "trash"}".html_safe + " " +@restaurant.name, restaurant_path(@restaurant), method: :delete, class: "rest-show-link" %><br>
<% end %>

 <%= link_to "#{fa_icon "undo"}".html_safe + " All Restaurants", restaurants_path, class: "rest-show-link"   %>