config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback', to: 'sessions#github_create'
  get '/auth/google_oauth2/callback', to: 'sessions#google_create'
  get '/auth/twitter/callback', to: 'sessions#twitter_create'
  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#home'
  post '/login' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/user' => 'users#show'

  get '/all_restaurants_in_database' => 'locations#all_restaurants_in_db'

  resources :locations
  resources :restaurants
  resources :items

  resources :restaurants, only: [:show, :index] do
    resources :items
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user, optional: true
  belongs_to :restaurant, optional: true
  validates_presence_of :state, { message: "State can't be blank"}

  def city_and_state
    if self.city == nil || self.city == ""
      self.state
    else
      self.city + ", " + self.state
    end
  end

  def self.options
    self.select(:state).distinct.order(:state)
  end

  def self.search(search)
    if search
      location = Location.find_by(state: search)
      if location
        self.where(state: location.state).order(:city)
      else
        self.all.order(:city)
      end
    else
      self.all.order(:city)
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :require_login
    def all_restaurants_in_db
       if params[:query_search] && params[:query_existing] == ""
         @location = Location.search(params[:query_search])
         if @location.sort_by{|obj| obj.id} == Location.all.sort_by{|obj| obj.id}
            @state = "State Not Found - Below Are All Restaurants"
         else
           @state = params[:query_search]
         end
       elsif params[:query_existing] && params[:query_search] == ""
         @location = Location.search(params[:query_existing])
         @state = params[:query_existing]
       else
         @location = Location.search("all")
         @state = "All Results  "
       end
       render 'all_restaurants_in_db'
     end

     def restaurant_params
       params.require(:location).permit(:query_search, :query_existing, :city, :state)
     end
   end

app/views/locations/all_restaurants_in_db.html.erb
<h1>All Restaurants in the Database</h1>
<h2 ><u>Search State:</u></h2>

<%= form_tag all_restaurants_in_database_path, method: :get do %>
  <p class='search'>
    Enter State: <%= text_field_tag :query_search %>

    OR Select Existing State:

    <%=select_tag :query_existing, options_from_collection_for_select(Location.options, :state, :state, :state), prompt: "Please Select"%>
    &nbsp &nbsp &nbsp<%= button_to "Search State", {}, {class: 'search-state'}%>
    <%= button_to "Clear Filter", all_restaurants_in_database_path, method: :get%>
  </p>
<% end %>

<h3><%= @state %></h3>
<% if @location%>
    <% @location.each do |l| %>
      <ul>
        <li><%=link_to l.restaurant.name, restaurant_path(l.restaurant)%> - <%= l.city_and_state %> </li>
        <div class="itemNames-<%=l.restaurant.id%> "></div><br>
        <button class="show" data-id="<%= l.restaurant.id %>">Show Menu</button>
        <button class="hide" data-id="<%= l.restaurant.id %>">Hide Menu</button>
      </ul>
    <% end %>
  <% end %>